services:
  mysql:
    image: mysql:8.0
    container_name: SleeperDbContainer
    restart: always
    networks:
      - sleeper
    environment:
      MYSQL_ROOT_PASSWORD: L0caldev
      MYSQL_DATABASE: SleeperDb
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  sleeperdashboard:
    container_name: SleeperDashboardContainer
    image: ${DOCKER_REGISTRY-}sleeperdashboard
    build:
      context: .
      dockerfile: SleeperDashboard/Dockerfile
    ports:
        - "8080"  # Map container's 8080
    networks:
        - sleeper
    depends_on:
        - mysql
    environment:
        #ASPNETCORE_URLS: "https://+:8003" # Forces the app to use the correct URL
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://0.0.0.0:8080
        - ConnectionStrings__SleeperDb=Server=mysql;Database=SleeperDb;User=root;Password=L0caldev;
        - ASPNETCORE_Kestrel__Certificates__Default__Password=
        - ASPNETCORE_Kestrel__Certificates__Default__Path/https/aspnetapp.pfx
        
    command: ["dotnet", "SleeperDashboard.dll"]
    volumes:
      - ~/.aspnet/https:/https:ro
    
volumes:
    mysql: {}
      
networks:
    sleeper:
       driver: bridge
      
