// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleeperDashboard.Data;

#nullable disable

namespace SleeperDashboard.Migrations
{
    [DbContext(typeof(SleeperDbContext))]
    [Migration("20250325010348_AddSomeMoreTables")]
    partial class AddSomeMoreTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.FantasyPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("FantasyPosition");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllowPnInactiveStarters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AllowPnPlayerInjuryStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AllowPnScoring")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestrictPnScoringStartersOnly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Streak")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("College")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DepthChartOrder")
                        .HasColumnType("int");

                    b.Property<string>("DepthChartPosition")
                        .HasColumnType("longtext");

                    b.Property<string>("EspnId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FantasyDataId")
                        .HasColumnType("int");

                    b.Property<string>("FantasyPositions")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hashtag")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Height")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InjuryStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InjuryStatus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("PracticeParticipation")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("RosterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RosterId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("RosterId2")
                        .HasColumnType("bigint");

                    b.Property<string>("RotowireId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RotoworldId")
                        .HasColumnType("int");

                    b.Property<string>("SearchFirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchFullName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchLastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SearchRank")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SportradarId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StatsId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Team")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Weight")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("YahooId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("YearsExp")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("RosterId");

                    b.HasIndex("RosterId1");

                    b.HasIndex("RosterId2");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Roster", b =>
                {
                    b.Property<long>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CoOwners")
                        .HasColumnType("longtext");

                    b.Property<string>("Keepers")
                        .HasColumnType("longtext");

                    b.Property<string>("LeagueId")
                        .HasColumnType("longtext");

                    b.Property<int>("MetadataId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerMap")
                        .HasColumnType("longtext");

                    b.Property<string>("Taxi")
                        .HasColumnType("longtext");

                    b.HasKey("RosterId");

                    b.HasIndex("MetadataId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<long?>("RosterId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RosterId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Player", b =>
                {
                    b.HasOne("SleeperDashboard.Data.Entity.Roster", null)
                        .WithMany("Players")
                        .HasForeignKey("RosterId");

                    b.HasOne("SleeperDashboard.Data.Entity.Roster", null)
                        .WithMany("Reserve")
                        .HasForeignKey("RosterId1");

                    b.HasOne("SleeperDashboard.Data.Entity.Roster", null)
                        .WithMany("Starters")
                        .HasForeignKey("RosterId2");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Roster", b =>
                {
                    b.HasOne("SleeperDashboard.Data.Entity.Metadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Setting", b =>
                {
                    b.HasOne("SleeperDashboard.Data.Entity.Roster", null)
                        .WithMany("Settings")
                        .HasForeignKey("RosterId");
                });

            modelBuilder.Entity("SleeperDashboard.Data.Entity.Roster", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Reserve");

                    b.Navigation("Settings");

                    b.Navigation("Starters");
                });
#pragma warning restore 612, 618
        }
    }
}
